### PR TITLE
fix: ios crash on launch

### LINKED ISSUE #109: Not getting crash reports on iOS or Android
Looking for some guidance on where I might have gone wrong

Trying to integrate the BugSplat plugin with Unreal Engine 5.5.1

I've included the BugSplat plugin in our engine plugins folder, and ran into a few issues:

#**1 Source/BugSplat/private/BugSplat.cpp needs to include PropertyEditorModule** - it's not currently including it, and was causing build failures

**#2 Android Symbols weren't uploading**:
the UPL is adding a task to run after:
                            task.name == 'ue4CompleteDebug' ||
                            task.name == 'ue4CompleteRelease' ||
                            task.name == 'ueCompleteDebug' ||
                            task.name == 'ueCompleteRelease'

But when we run our CI build, there is no Gradle task with that name - I have included
                            task.name == 'ueCompleteBundleDebug' ||
                            task.name == 'ueCompleteBundleRelease'
As that's the closest task naming I could find to the task BugSplat is trying to run after

After that, the Symbol upload would fail because the directory the plugin is searching for Symbols in was empty - it was searching in:
$S(BuildDir)/gradle/app/build/intermediates/merged_native_libs/release
But our CI pipeline isn't outputting anything to that location - the relevant files are actually at this location for us:
$S(BuildDir)/../gradle/app/build/intermediates/merged_native_libs/release

BugSplat is checking whether we're running "Shipping" config to decide whether to upload symbols from the release or debug configuration - but this seems wrong, I believe UE is using Release for Development & Test builds (These are the build configurations we're using)

**#3 iOS Symbols weren't uploading**:
I've uploaded the mac uploader script to use this targetName.dSYM directory instead of the one at latest (targetName.app.dSYM), because the .app.dsym file doesn't exist in our output binaries
export dsymFileSpec="$targetName.app.dSYM"
export dsymFileSpec="$targetName.dSYM"

**#4 iOS is crashing on launch** - After all this iOS crashes on launch, unfortunately with no crash report (I don't currently have access to a Mac to get a crash dump from XCode)

**#5 Android builds don't upload crash reports** - now that Android is building, and symbols are uploading, I can see the Android versions in the BugSplat dashboard, but when we crash (either using the "debug crash" command, or through legitimate game crashes) nothing is reported to the BugSplat dashboard

I'm not sure what I've done wrong here - any guidance?

### PR DESCRIPTION
**Pull request by bobbyg603**
### Description

* Fixes issue 'Library not loaded: @rpath/BugSplat.framework/BugSplat' by modifying BugSplatRuntime.Build.cs to set `bCopyFramework` to true as seen [here](https://rassadin.net/posts/swift-frameworks-unreal/).
* Adds HockeySDK with statically linked libCrashReporter.a to avoid symbol collisions
* Adds HockeySDK.framework/embeddedframework as PublicAdditionalFrameworks
* Signs BugSplat.framework and HockeySDK.framework with the BugSplat distribution certificate.

Fixes #109

### Checklist

- [x] Tested manually
- [x] Unit tests pass with no errors or warnings
- [x] Documentation updated (if applicable)
- [x] Reviewed by at least 1 other contributor

### CODE REVIEW

File: Source/ThirdParty/IOS/BugSplat.framework/Headers/BugSplatDelegate.h [hunk 1]
```diff
@@ -59,7 +59,22 @@ NS_ASSUME_NONNULL_BEGIN
...
+
+ BugSplatAttachment *attachment = [[BugSplatAttachment alloc] initWithFilename:@"myfile.data"
+                                                                attachmentData:data
+                                                                   contentType:@"application/octet-stream"];
+ @param bugSplat The `BugSplat` instance invoking this delegate
+*/
+- (BugSplatAttachment *)attachmentForBugSplat:(BugSplat *)bugSplat API_AVAILABLE(ios(13.0));
+
 // MARK: - BugSplatDelegate (MacOS)
+#if TARGET_OS_OSX
```
Comment (bobbyg603) [inline Source/ThirdParty/IOS/BugSplat.framework/Headers/BugSplatDelegate.h:77]: wait where did this come from

Comment (bobbyg603) [reply Source/ThirdParty/IOS/BugSplat.framework/Headers/BugSplatDelegate.h:77]: oh nvm

**Review by daveplunkett — APPROVED** [review]
